"""SOURCE-only independently constructed fixtures; no capture/model loaded."""
import unittest
from p02_cross_discrete import join, rank_join
from p02_discrete_schema import RUST_REQUIRED


def fixture(rank=0):
    # Deliberately simple synthetic native state and nonconsuming future.
    # Neither is read from Rust/Julia results or generated by either RNG.
    words = list(range(624))
    future = list(reversed(words))
    r = {key: [0] * size for key, size in RUST_REQUIRED.items()}
    shared = {
        'd:seed': [rank + 1], 'd:group': [rank, 0, 1],
        'd:steps': [1], 'd:status': [0], 'd:configured-samples': [3],
        'd:chain-samples': [3], 'd:requested-width': [1],
        'd:initial-rng': future, 'd:rng': future,
        'd:initial-draw-count': [2], 'd:total-draw-count': [4],
        'd:sampling-draw-count': [2], 'd:acceptance-events': [1, 0],
        **{f'd:{key}': [0] * size for key, size in (
            ('ele_idx', 18), ('ele_cfg', 36), ('ele_num', 36),
            ('ele_proj_cnt', 6), ('counter', 10), ('local-counter', 10),
            ('reduced-counter', 10))},
        'n:initial-parameters': [0] * 28, 'n:parameters': [0] * 28,
    }
    r.update(shared)
    j = {key: value.copy() for key, value in shared.items()}
    for label, raw_key, cursor_key, cursor, count in (
        ('seeded', 'before-init-raw-rng', 'before-init-rng-cursor', 624, 0),
        ('initialized', 'initial-raw-rng', 'initial-rng-cursor', 2, 2),
        ('checkpoint-0', 'checkpoint-000000-raw624', 'checkpoint-000000-cursor', 4, 4),
        ('final', 'raw-rng', 'rng-cursor', 4, 4),
    ):
        r['d:' + raw_key] = words.copy()
        r['d:' + cursor_key] = [cursor]
        j.update({f'd:{label}-raw624': words.copy(), f'd:{label}-cursor': [cursor],
                  f'd:{label}-initialized': [1],
                  f'd:{label}-raw-abi': [1, 19937, 156, 624, 312, 16, 4, cursor, 1, 1],
                  f'd:{label}-observed-primitive-words': [count]})
    r['d:checkpoint-000000-native-words-consumed'] = [4]
    saved = [8]
    for size in (18, 36, 36, 6, 0, 10):
        saved += [size] + [0] * size
    saved += [624] + future
    # Actual schema shapes, synthetic values: proposal, draw, decision, saved.
    events = [[0, 1], [1, 0, 1, 0, 0, 0], [2, 0, 1, 0, 0, 1, 2, 0],
              [9, 123], [7, 1, 123], saved]
    for records, sequence in ((r, events + [[10, 4, 4] + words]), (j, events)):
        records['d:trace-events'] = [len(sequence)]
        records.update({f'd:trace-{i:06}': e.copy() for i, e in enumerate(sequence)})
    r['d:trace-schema'] = [2]
    r['d:requested-record-schema'] = [2]
    return r, j


def text(records):
    return ''.join(key + ' ' + ' '.join(map(str, value)) + '\n'
                   for key, value in records.items())


class CrossDiscreteControls(unittest.TestCase):
    def test_unknown_discrete_writer_key_rejected(self):
        for implementation in (0, 1):
            pair = fixture()
            pair[implementation]['d:unapproved-ordinary-field'] = [0]
            with self.subTest(implementation=implementation), self.assertRaisesRegex(ValueError, 'unknown discrete'):
                rank_join(text(pair[0]), text(pair[1]), 0)

    def test_missing_or_wrongshape_local_reduced_counter_rejected(self):
        for implementation in (0, 1):
            for key in ('d:local-counter', 'd:reduced-counter'):
                for size in (None, 1, 9, 11):
                    pair = fixture()
                    if size is None:
                        del pair[implementation][key]
                    else:
                        pair[implementation][key] = [0] * size
                    with self.subTest(implementation=implementation, key=key, size=size), self.assertRaisesRegex(ValueError, 'counter plane'):
                        rank_join(text(pair[0]), text(pair[1]), 0)

    def test_empty_counter_row_rejected_by_strict_parser(self):
        for implementation in (0, 1):
            for key in ('d:local-counter', 'd:reduced-counter'):
                pair = fixture()
                pair[implementation][key] = []
                with self.subTest(implementation=implementation, key=key), self.assertRaisesRegex(ValueError, 'invalid record at line'):
                    rank_join(text(pair[0]), text(pair[1]), 0)

    def test_both_ranks_positive_count_provenance(self):
        pairs = [fixture(i) for i in range(2)]
        result = join([text(p[0]) for p in pairs], [text(p[1]) for p in pairs])
        self.assertEqual([r['rank'] for r in result], [0, 1])
        self.assertTrue(all(r['julia_native_draw_counter'] == 'Unavailable' for r in result))
        self.assertTrue(all(not r['numerical_acceptance'] for r in result))

    def test_every_raw_boundary_and_cursor_mutation(self):
        for label in ('seeded', 'initialized', 'checkpoint-0', 'final'):
            for suffix in ('raw624', 'cursor'):
                r, j = fixture()
                j[f'd:{label}-{suffix}'][0] += 1
                with self.subTest(label=label, suffix=suffix), self.assertRaises(ValueError):
                    rank_join(text(r), text(j), 0)

    def test_observed_count_and_future_mutation(self):
        for key in ('d:initialized-observed-primitive-words',
                    'd:checkpoint-0-observed-primitive-words',
                    'd:final-observed-primitive-words', 'd:initial-rng', 'd:rng'):
            r, j = fixture()
            j[key][0] += 1
            with self.subTest(key=key), self.assertRaises(ValueError):
                rank_join(text(r), text(j), 0)

    def test_proposal_decision_saved_and_saved_future_mutation(self):
        for event, component in ((1, 1), (2, 1), (4, 1), (4, 2), (5, 2), (5, -1)):
            r, j = fixture()
            j[f'd:trace-{event:06}'][component] += 1
            with self.subTest(event=event, component=component), self.assertRaises(ValueError):
                rank_join(text(r), text(j), 0)

    def test_final_config_counters_and_acceptance_mutation(self):
        for key in ('ele_idx', 'ele_cfg', 'ele_num', 'ele_proj_cnt', 'counter',
                    'local-counter', 'reduced-counter', 'acceptance-events'):
            r, j = fixture()
            j['d:' + key][0] += 1
            with self.subTest(key=key), self.assertRaises(ValueError):
                rank_join(text(r), text(j), 0)

    def test_missing_duplicate_unknown_event(self):
        r, j = fixture()
        original = text(j)
        for bad in (original.replace('d:trace-000001 ', 'd:missing-event ', 1),
                    original + 'd:trace-000001 1 0 1 0 0 0\n',
                    original.replace('d:trace-000000 0 1', 'd:trace-000000 99 1')):
            with self.assertRaises(ValueError):
                rank_join(text(r), bad, 0)

    def test_rank_inventory_seed_group_and_settings(self):
        for key in ('seed', 'group', 'configured-samples', 'chain-samples', 'requested-width'):
            r, j = fixture()
            r['d:' + key][0] += 1
            j['d:' + key][0] += 1
            with self.subTest(key=key), self.assertRaises(ValueError):
                rank_join(text(r), text(j), 0)
        for rank in (True, -1, 2):
            r, j = fixture()
            with self.assertRaises(ValueError):
                rank_join(text(r), text(j), rank)
        with self.assertRaises(ValueError):
            join([], [])

    def test_raw_extension_not_discarded_unchecked(self):
        for mutation in ('missing', 'duplicate', 'nonterminal', 'changed-state'):
            r, j = fixture()
            if mutation == 'missing':
                del r['d:trace-000006']
                r['d:trace-events'] = [6]
            elif mutation == 'duplicate':
                r['d:trace-000007'] = r['d:trace-000006'].copy()
                r['d:trace-events'] = [8]
            elif mutation == 'nonterminal':
                r['d:trace-000007'] = [9, 0]
                r['d:trace-events'] = [8]
            else:
                r['d:trace-000006'][3] += 1
            with self.subTest(mutation=mutation), self.assertRaises(ValueError):
                rank_join(text(r), text(j), 0)
