//! Grouped (`NSplitSize > 1`) runs that mVMC C defines (issue #349).
//!
//! FSZ PhysCal, FSZ ParaOpt with `NQPFull > 1`, Lanczos PhysCal and OptTrans
//! with `NQPOptTrans > 1` give defined results in the native C executable at 2
//! and 4 ranks. The expected values are native C `vmc.out` outputs checked in
//! under `tests/fixtures/grouped_nsplit_349/` (provenance in `PROVENANCE.txt`,
//! regenerated by `c_toolbox/grouped_nsplit_349/generate.sh`). Ordinary tests
//! never run C. SR-CG grouped runs stay rejected (undefined in C, see
//! `validation.rs`).
//!
//! * `c_grouped_fixtures_equal_c_ungrouped_chains` (always runs) pins the C
//!   evidence: a one-group C run equals the single-rank run with the same seed,
//!   and `4 ranks / NSplitSize 2` equals `2 ranks / NSplitSize 1` (the same two
//!   seeds), so C's QP/sample splitting and reductions are complete.
//! * `grouped_runs_match_c_fixtures_and_serial_chain` (explicit MPI run) runs
//!   the public Rust entry points with an actual group communicator and compares
//!   against the C fixture of the same world/split and, for a single group,
//!   against the serial Rust chain.
//!
//! Explicit MPI command (inside the Dev Container, see docs/DEV_CONTAINER.md):
//! build with `--features mpi` and run the test binary as
//! `MPI_ISSUE349_OUTPUT=<new dir> mpiexec -n {2,4} <binary> --ignored --exact
//! grouped_runs_match_c_fixtures_and_serial_chain --nocapture`.

use std::{
    fs,
    path::{Path, PathBuf},
};

#[cfg_attr(not(feature = "mpi"), allow(dead_code))]
struct Case {
    id: String,
    model: String,
    phys: bool,
    opt_trans: bool,
    compare_c: bool,
}

fn fixture_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/grouped_nsplit_349")
}

fn cases() -> Vec<Case> {
    let text = fs::read_to_string(fixture_root().join("cases.txt")).unwrap();
    text.lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .map(|line| {
            let f: Vec<_> = line.split_whitespace().collect();
            assert_eq!(f.len(), 5, "{line}");
            Case {
                id: f[0].into(),
                model: f[1].into(),
                phys: f[2] == "phys",
                opt_trans: f[3] == "1",
                compare_c: f[4] == "1",
            }
        })
        .collect()
}

#[cfg_attr(not(feature = "mpi"), allow(dead_code))]
fn overrides(case: &Case) -> Vec<(String, String)> {
    let text = fs::read_to_string(fixture_root().join(&case.id).join("overrides.txt")).unwrap();
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| {
            let (key, value) = line.split_once(' ').unwrap();
            (key.to_owned(), value.to_owned())
        })
        .collect()
}

fn numbers(path: &Path) -> Vec<f64> {
    fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()))
        .split_whitespace()
        .map(|token| token.parse::<f64>().unwrap())
        .collect()
}

/// Largest `|a - b| / (1 + |b|)` over a file pair; panics on a shape mismatch.
fn scaled_difference(a: &Path, b: &Path) -> f64 {
    let (x, y) = (numbers(a), numbers(b));
    assert_eq!(x.len(), y.len(), "{} vs {}", a.display(), b.display());
    x.iter()
        .zip(&y)
        .map(|(u, v)| {
            assert!(u.is_finite() && v.is_finite());
            (u - v).abs() / (1.0 + v.abs())
        })
        .fold(0.0, f64::max)
}

fn c_dir(case: &Case, world: usize, split: usize) -> PathBuf {
    fixture_root()
        .join(&case.id)
        .join(format!("c/r{world}s{split}"))
}

fn file_names(dir: &Path) -> Vec<String> {
    let mut names: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .map(|entry| entry.unwrap().file_name().into_string().unwrap())
        .collect();
    names.sort();
    names
}

/// C grouped versus C ungrouped, scaled differences (`|a-b|/(1+|b|)`).
///
/// Observed maxima over the fixtures: PhysCal <= 3.5e-15 (Lanczos 7.9e-14);
/// ParaOpt 2.2e-10 (FSZ, SR-solve amplification of reduction-order roundoff)
/// and 9.2e-14 (OptTrans). The bounds leave about 40x to 4e3x margin and are
/// far below the O(1e-2) a lost QP or sample slice would produce.
fn c_tolerance(case: &Case) -> f64 {
    if case.phys {
        1e-11
    } else {
        1e-8
    }
}

#[test]
fn c_grouped_fixtures_equal_c_ungrouped_chains() {
    for case in cases() {
        // One group of width W reproduces the single-rank chain (same seed);
        // four ranks in groups of two reproduce two independent seeded chains.
        for ((wa, sa), (wb, sb)) in [((1, 1), (2, 2)), ((1, 1), (4, 4)), ((2, 1), (4, 2))] {
            let a = c_dir(&case, wa, sa);
            let b = c_dir(&case, wb, sb);
            let names = file_names(&a);
            assert!(!names.is_empty());
            assert_eq!(names, file_names(&b), "{}", case.id);
            for name in names {
                let diff = scaled_difference(&a.join(&name), &b.join(&name));
                assert!(
                    diff <= c_tolerance(&case),
                    "{} {name}: C r{wa}s{sa} vs r{wb}s{sb} scaled diff {diff:e}",
                    case.id
                );
            }
        }
    }
}

#[cfg(feature = "mpi")]
mod mpi_run {
    use super::*;
    use mvmc_core::{
        prepare_phys_cal_from_namelist_with_reducer_and_opt_trans,
        run_para_opt_from_namelist_with_reducer, vmc_phys_cal_with_reducer, InitialDef, Reducer,
        RunConfig, SingleProcessReducer,
    };

    /// Copy the case inputs and apply its overrides plus `NSplitSize`.
    fn prepare_inputs(case: &Case, dest: &Path, split: usize) -> (PathBuf, PathBuf) {
        let source = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/physcal_181")
            .join(&case.model);
        let inputs = dest.join("inputs");
        fs::create_dir_all(&inputs).unwrap();
        for entry in fs::read_dir(source.join("inputs")).unwrap() {
            let entry = entry.unwrap();
            fs::copy(entry.path(), inputs.join(entry.file_name())).unwrap();
        }
        fs::copy(source.join("zqp_opt.dat"), dest.join("zqp_opt.dat")).unwrap();
        let mut settings = overrides(case);
        settings.push(("NSplitSize".into(), split.to_string()));
        let modpara = inputs.join("modpara.def");
        let mut lines: Vec<String> = fs::read_to_string(&modpara)
            .unwrap()
            .lines()
            .map(str::to_owned)
            .collect();
        for (key, value) in settings {
            let line = lines
                .iter_mut()
                .find(|line| line.split_whitespace().next() == Some(key.as_str()))
                .unwrap_or_else(|| panic!("{key} missing from modpara.def"));
            *line = format!("{key} {value}");
        }
        fs::write(&modpara, lines.join("\n") + "\n").unwrap();
        (inputs.join("namelist.def"), dest.join("zqp_opt.dat"))
    }

    /// Run the public entry point of `case` with `reducer`; returns the output dir.
    fn run<R: Reducer + ?Sized>(case: &Case, dest: &Path, split: usize, reducer: &R) -> PathBuf {
        let (namelist, fixed) = prepare_inputs(case, dest, split);
        let data = mvmc_expert_parsers::parse_expert_mode_files_with_c_opt_trans(
            &namelist,
            case.opt_trans,
        )
        .unwrap();
        // Same label inference as the CLI.
        let mode = if data.i_flg_orbital_general != 0 {
            "fsz"
        } else if mvmc_core::get_all_complex_flag(&data).unwrap() {
            "cmp"
        } else {
            "real"
        };
        let out = dest.join("out");
        if case.phys {
            let preparation = prepare_phys_cal_from_namelist_with_reducer_and_opt_trans(
                &namelist,
                &fixed,
                mode,
                None,
                reducer,
                case.opt_trans,
            )
            .unwrap();
            vmc_phys_cal_with_reducer(preparation, Some(&out), reducer).unwrap();
        } else {
            let mut config = RunConfig::new(data.modpara.nsr_opt_itr_step, mode);
            config.initial_def = InitialDef::Path(fixed);
            config.output_dir = Some(out.clone());
            config.enable_opt_trans = Some(case.opt_trans);
            run_para_opt_from_namelist_with_reducer(&namelist, config, reducer).unwrap();
        }
        out
    }

    /// Rust names the ParaOpt files without C's `_001` data-index suffix.
    fn rust_name(case: &Case, c_name: &str) -> String {
        if case.phys {
            c_name.to_owned()
        } else {
            c_name.replace("_001", "")
        }
    }

    /// Rust versus C. Observed Rust-vs-C scaled maxima, ungrouped and grouped
    /// alike: PhysCal 2.4e-11 (complex FSZ, NQPFull = 2), ParaOpt 7e-10.
    fn c_reference_tolerance(case: &Case) -> f64 {
        if case.phys {
            1e-9
        } else {
            1e-8
        }
    }

    /// Rust one-group versus serial Rust chain. Observed <= 3e-13 (reduction
    /// order only); the bounds keep >300x margin below O(1e-2) slice losses.
    fn serial_tolerance(case: &Case) -> f64 {
        if case.phys {
            1e-10
        } else {
            1e-9
        }
    }

    #[test]
    #[ignore = "explicit native 2/4-rank MPI run; see the module documentation"]
    fn grouped_runs_match_c_fixtures_and_serial_chain() {
        let world = mvmc_core::mpi::MpiContext::initialize().unwrap();
        let ranks = world.world_size();
        assert!(matches!(ranks, 2 | 4), "run with mpiexec -n 2 or 4");
        let root = PathBuf::from(std::env::var_os("MPI_ISSUE349_OUTPUT").unwrap());
        let setup = if world.is_root() {
            fs::create_dir(&root)
        } else {
            Ok(())
        };
        assert!(!world.any_failure(setup.is_err()), "{setup:?}");
        let local = root.join(format!("rank-{}", world.rank()));
        fs::create_dir(&local).unwrap();
        for case in cases() {
            for width in [1, 2, 4].into_iter().filter(|width| *width <= ranks) {
                let group = world.split_groups(width).unwrap();
                let dest = local.join(format!("{}-w{width}", case.id));
                let out = run(&case, &dest, width, &group);
                world.barrier();
                if world.is_root() {
                    let reference = c_dir(&case, ranks, width);
                    for name in file_names(&reference) {
                        let actual = out.join(rust_name(&case, &name));
                        if case.compare_c {
                            let diff = scaled_difference(&actual, &reference.join(&name));
                            assert!(
                                diff <= c_reference_tolerance(&case),
                                "{} world {ranks} width {width} {name}: Rust vs C scaled diff {diff:e}",
                                case.id
                            );
                        }
                        println!(
                            "ISSUE349 case={} world={ranks} width={width} file={name} compare_c={}",
                            case.id, case.compare_c
                        );
                    }
                    if width == ranks {
                        // One group is the serial chain with the same seed.
                        let serial = run(
                            &case,
                            &local.join(format!("{}-serial-w{width}", case.id)),
                            1,
                            &SingleProcessReducer,
                        );
                        for name in file_names(&reference) {
                            let rust = rust_name(&case, &name);
                            let diff = scaled_difference(&out.join(&rust), &serial.join(&rust));
                            assert!(
                                diff <= serial_tolerance(&case),
                                "{} world {ranks}: grouped vs serial Rust {name} scaled diff {diff:e}",
                                case.id
                            );
                        }
                    }
                }
                world.barrier();
            }
        }
    }
}
