//! Focused original optimizer integration contracts (#184).
//! Mathematical expectations are analytic, not generated by Rust/C/Julia.
//! Green comparison is a test-helper contract, not a new production API.

#[path = "../../../tests/support/numerical_comparison.rs"]
mod numerical_comparison;

use mvmc_expert_parsers::utils::qp_weight::{gauss_legendre, legendre_poly};

#[test]
fn optimizer_integration_legendre_original_points_and_endpoint_loop() {
    // Original runtests.jl M0477..M0481: x=1/2, degrees 0..3, then
    // every degree 0..5 at x=1. Endpoint identity is not covered merely by
    // running a sampled optimizer or the existing P0..P3 midpoint test.
    assert_eq!(legendre_poly(0.5, 0), 1.0);
    assert_eq!(legendre_poly(0.5, 1), 0.5);
    for (degree, expected) in [(2, -0.125), (3, -0.4375)] {
        numerical_comparison::assert_close(
            legendre_poly(0.5, degree),
            expected,
            16.0 * (degree + 1) as f64 * f64::EPSILON,
            16.0 * (degree + 1) as f64 * f64::EPSILON,
            format!("original P{degree}(1/2)"),
        );
    }
    for degree in 0..=5 {
        let bound = 16.0 * (degree + 1) as f64 * f64::EPSILON;
        numerical_comparison::assert_close(
            legendre_poly(1.0, degree),
            1.0,
            bound,
            bound,
            format!("original P{degree}(1)"),
        );
    }
}

#[test]
fn optimizer_integration_one_node_pi_interval_is_midpoint_and_length() {
    let (nodes, weights) = gauss_legendre(0.0, std::f64::consts::PI, 1);
    assert_eq!((nodes.len(), weights.len()), (1, 1));
    let bound = 16.0 * f64::EPSILON;
    numerical_comparison::assert_close(
        nodes[0],
        std::f64::consts::FRAC_PI_2,
        bound,
        bound,
        "original pi interval midpoint",
    );
    numerical_comparison::assert_close(
        weights[0],
        std::f64::consts::PI,
        bound,
        bound,
        "original pi interval length",
    );
}

#[test]
fn optimizer_integration_five_node_quadrature_preserves_interval_and_quartic() {
    // Exact original n=5, [-1,1], x^4 settings. Earlier fixture tests use
    // other orders on [0,pi] and do not establish this assertion literally.
    let (nodes, weights) = gauss_legendre(-1.0, 1.0, 5);
    assert_eq!((nodes.len(), weights.len()), (5, 5));
    assert!(nodes.iter().all(|x| (-1.0..=1.0).contains(x)));
    assert!(weights.iter().all(|w| w.is_finite() && *w > 0.0));
    // Five-term sum/root refinement: existing recurrence-roundoff scale,
    // not a solver-conditioning or long-run forward-error allowance.
    let bound = 16.0 * 6.0 * f64::EPSILON;
    numerical_comparison::assert_close(
        weights.iter().sum(),
        2.0,
        bound,
        bound,
        "original quadrature total weight",
    );
    let integral: f64 = nodes.iter().zip(&weights).map(|(x, w)| w * x.powi(4)).sum();
    numerical_comparison::assert_close(
        integral,
        2.0 / 5.0,
        bound,
        bound,
        "original quartic analytic integral",
    );
}

#[test]
fn green_helper_numeric_fields_are_bounded_but_indices_and_shape_are_exact() {
    // Analog of the developer-only Julia comparison tests; no claim about
    // its GreenCompareResult/exact/fallback flags or production file APIs.
    const REFERENCE: &str = "0 0 1 0 1.0 0.0\n1 1 0 1 2.0 0.0\n";
    let close = REFERENCE.replace("1.0 0.0", "1.00000000005 0.0");
    numerical_comparison::assert_numeric_text(
        &close,
        REFERENCE,
        1e-12,
        1e-10,
        &[0, 1, 2, 3],
        "one-body helper",
    );
    for bad in [
        REFERENCE.replace("1.0 0.0", "1.000000005 0.0"),
        REFERENCE.replace("1 1 0 1", "1 1 0 0"),
        "0 0 1 0 1.0 0.0\n".to_owned(),
        "0 0 1 0 1.0\n1 1 0 1 2.0 0.0\n".to_owned(),
    ] {
        assert!(
            std::panic::catch_unwind(|| numerical_comparison::assert_numeric_text(
                &bad,
                REFERENCE,
                1e-12,
                1e-10,
                &[0, 1, 2, 3],
                "one-body negative"
            ))
            .is_err()
        );
    }
}

#[test]
fn green_helper_quantity_bounds_do_not_permit_factored_layout_drift() {
    let reference = "1.0 0.0\n";
    let nearby = "1.0000000005 0.0\n";
    assert!(
        std::panic::catch_unwind(|| numerical_comparison::assert_numeric_text(
            nearby,
            reference,
            1e-12,
            1e-10,
            &[],
            "linear quantity"
        ))
        .is_err()
    );
    numerical_comparison::assert_numeric_text(
        nearby,
        reference,
        1e-12,
        1e-9,
        &[],
        "product quantity",
    );
    for bad in ["2.5 -1.0\n0.3 0.1\n", "2.5 -1.0\n"] {
        assert!(
            std::panic::catch_unwind(|| numerical_comparison::assert_numeric_text(
                bad,
                "2.5 -1.0 0.3 0.1\n",
                1e-12,
                1e-9,
                &[],
                "factored layout"
            ))
            .is_err()
        );
    }
    // Identical malformed multi-line pairs are NOT rejected by this generic
    // helper. Julia's schema-specific single-line validation is a distinct
    // SOURCE_ONLY helper requirement, not silently labelled reproduced here.
}
