//! C MultiDef mode `vmc.out -m N DirListFile NameListFile [OptParaFile]` (issue #348).
//!
//! References are native C `vmc.out -m 2` outputs and messages checked in under
//! `tests/fixtures/multidef_348/` (provenance in `PROVENANCE.txt`, regenerated by
//! `c_toolbox/multidef_348/generate_c_runs.sh`). Ordinary tests never run C. Two
//! directories hold different inputs: `a` is `physcal_181/heisenberg_chain_real`, `b` is
//! `physcal_181/hubbard_chain_real`; the optional initial-parameter argument
//! `zqp_opt.dat` is resolved inside each group's directory.
//!
//! * The serial tests run everywhere (a one-rank world, only `-m 1`).
//! * `multidef_groups_match_own_single_runs_and_c_fixture` is an explicit MPI gate
//!   (`#[ignore]`, feature `mpi`; run by `scripts/run_explicit_mpi_gates.sh`).
//!
//! Float tolerances follow docs/NUMERICAL_COMPARISONS.md (scaled difference
//! `|a-b|/(1+|b|)`): Rust group vs Rust standalone run of the same width 1e-12 (identical
//! algorithm and reduction order; the run is not required to be bitwise equal), Rust vs
//! native C 1e-9 (PhysCal bound of `tests/fixtures/grouped_nsplit_349/README.md`).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

const FILES: [&str; 5] = [
    "zvo_out_001.dat",
    "zvo_var_001.dat",
    "zvo_cisajs_001.dat",
    "zvo_cisajscktalt_001.dat",
    "zvo_cisajscktaltex_001.dat",
];

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn fixture(path: &str) -> PathBuf {
    repo().join("tests/fixtures/multidef_348").join(path)
}

struct TestDir(PathBuf);

impl TestDir {
    fn new(name: &str) -> Self {
        let path = std::env::temp_dir().join(format!("mvmc-348-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).unwrap();
        Self(path)
    }
}

impl Drop for TestDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

/// `root/a` and `root/b` with the two models' inputs and `zqp_opt.dat`, plus `dirs.txt`.
fn setup(root: &Path) {
    for (dir, model) in [("a", "heisenberg_chain_real"), ("b", "hubbard_chain_real")] {
        let source = repo().join("tests/fixtures/physcal_181").join(model);
        let target = root.join(dir);
        fs::create_dir_all(&target).unwrap();
        for entry in fs::read_dir(source.join("inputs")).unwrap().flatten() {
            if entry.path().is_file() {
                fs::copy(entry.path(), target.join(entry.file_name())).unwrap();
            }
        }
        fs::copy(source.join("zqp_opt.dat"), target.join("zqp_opt.dat")).unwrap();
    }
    fs::write(root.join("dirs.txt"), "a\nb\n").unwrap();
}

fn mvmc() -> Command {
    let mut command = Command::new(env!("CARGO_BIN_EXE_mvmc"));
    command
        .env("OPENBLAS_NUM_THREADS", "1")
        .env("OMP_NUM_THREADS", "1")
        .env_remove("OMPI_COMM_WORLD_SIZE")
        .env_remove("PMI_SIZE");
    command
}

fn numbers(path: &Path) -> Vec<f64> {
    fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()))
        .split_whitespace()
        .map(|token| token.parse::<f64>().unwrap())
        .collect()
}

/// Largest `|a - b| / (1 + |b|)` over a file pair; panics on a shape mismatch.
fn scaled_difference(a: &Path, b: &Path) -> f64 {
    let (x, y) = (numbers(a), numbers(b));
    assert_eq!(x.len(), y.len(), "{} vs {}", a.display(), b.display());
    x.iter()
        .zip(&y)
        .map(|(u, v)| {
            assert!(u.is_finite() && v.is_finite());
            (u - v).abs() / (1.0 + v.abs())
        })
        .fold(0.0, f64::max)
}

fn assert_outputs_close(actual: &Path, expected: &Path, tolerance: f64, context: &str) {
    for file in FILES {
        let diff = scaled_difference(&actual.join(file), &expected.join(file));
        assert!(
            diff <= tolerance,
            "{context}: {file} scaled difference {diff:e} > {tolerance:e}"
        );
    }
}

fn c_message(name: &str) -> String {
    fs::read_to_string(fixture(&format!("c_messages/{name}")))
        .unwrap()
        .trim_end()
        .to_owned()
}

fn first_stderr_line(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr)
        .lines()
        .next()
        .unwrap_or("")
        .to_owned()
}

#[test]
fn serial_m1_runs_in_the_listed_directory_like_a_plain_run() {
    let dir = TestDir::new("serial");
    setup(&dir.0);
    fs::write(dir.0.join("dirs.txt"), "b\n").unwrap();
    // Plain run in a copy of `b`.
    let plain = dir.0.join("plain");
    fs::create_dir_all(&plain).unwrap();
    for entry in fs::read_dir(dir.0.join("b")).unwrap().flatten() {
        fs::copy(entry.path(), plain.join(entry.file_name())).unwrap();
    }
    let status = mvmc()
        .current_dir(&plain)
        .args(["namelist.def", "zqp_opt.dat"])
        .output()
        .unwrap();
    assert!(
        status.status.success(),
        "{}",
        String::from_utf8_lossy(&status.stderr)
    );
    // MultiDef run: the namelist, the initial-parameter file and the default output
    // directory all resolve inside `b`.
    let multi = mvmc()
        .current_dir(&dir.0)
        .args(["-m", "1", "dirs.txt", "namelist.def", "zqp_opt.dat"])
        .output()
        .unwrap();
    assert!(
        multi.status.success(),
        "{}",
        String::from_utf8_lossy(&multi.stderr)
    );
    assert!(
        multi.stderr.is_empty(),
        "{}",
        String::from_utf8_lossy(&multi.stderr)
    );
    assert_outputs_close(
        &dir.0.join("b/output"),
        &plain.join("output"),
        1e-12,
        "serial -m 1",
    );
    assert!(!dir.0.join("a/output").exists());
    assert!(!dir.0.join("output").exists());
}

#[test]
fn m_option_is_cancelled_by_a_later_e_or_s_as_in_c() {
    let dir = TestDir::new("cancel");
    setup(&dir.0);
    // `-m 1 -e`: flagMultiDef is cleared, so the first positional is the namelist.
    let output = mvmc()
        .current_dir(dir.0.join("a"))
        .args(["-m", "1", "-e", "namelist.def", "zqp_opt.dat"])
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(dir.0.join("a/output/zvo_out_001.dat").is_file());
}

#[test]
fn error_messages_and_statuses_equal_native_c() {
    for (name, list, args) in [
        // C: size < N is an error before any file is read.
        ("size_lt_n", Some("a\nb\n"), ["-m", "2"]),
        ("missing_list", None, ["-m", "1"]),
        ("incomplete_list", Some(""), ["-m", "1"]),
        ("bad_dir", Some("nope\n"), ["-m", "1"]),
    ] {
        let dir = TestDir::new(name);
        setup(&dir.0);
        if let Some(content) = list {
            fs::write(dir.0.join("list.txt"), content).unwrap();
        }
        let output = mvmc()
            .current_dir(&dir.0)
            .args(args)
            .args(["list.txt", "namelist.def", "zqp_opt.dat"])
            .output()
            .unwrap();
        assert_eq!(
            output.status.code().map(|code| code.to_string()),
            Some(c_message(&format!("{name}.status"))),
            "{name}"
        );
        assert_eq!(
            first_stderr_line(&output),
            c_message(&format!("{name}.first_stderr_line")),
            "{name}"
        );
        assert!(!dir.0.join("a/output").exists(), "{name} ran a calculation");
    }
}

#[test]
fn nonpositive_n_is_rejected_where_c_divides_by_zero() {
    let dir = TestDir::new("nonpositive");
    setup(&dir.0);
    for n in ["0", "-1"] {
        let output = mvmc()
            .current_dir(&dir.0)
            .args(["-m", n, "dirs.txt", "namelist.def"])
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(1));
        assert_eq!(
            first_stderr_line(&output),
            "error: -m: N should be a positive integer."
        );
    }
}

#[test]
fn m_requires_a_directory_list_and_a_namelist() {
    let output = mvmc().args(["-m", "1", "dirs.txt"]).output().unwrap();
    assert!(!output.status.success());
    assert_eq!(first_stderr_line(&output), "error: Argument count mismatch");
    let output = mvmc()
        .args(["-m", "x", "dirs.txt", "n.def"])
        .output()
        .unwrap();
    assert!(!output.status.success());
    assert_eq!(
        first_stderr_line(&output),
        "error: -m: No digits were found"
    );
}

#[cfg(feature = "mpi")]
fn mpi_cli_command() -> Command {
    let version = Command::new("mpirun").arg("--version").output().unwrap();
    assert!(version.status.success(), "cannot identify MPI launcher");
    let metadata = format!(
        "{}{}",
        String::from_utf8_lossy(&version.stdout),
        String::from_utf8_lossy(&version.stderr)
    );
    let mut command = Command::new("timeout");
    command.args(["--kill-after=5s", "120s", "mpirun"]);
    if metadata.contains("Open MPI") || metadata.contains("OpenRTE") {
        command.arg("--oversubscribe");
    } else {
        assert!(
            metadata.contains("HYDRA build details"),
            "unsupported MPI launcher metadata: {metadata}"
        );
        command.arg("-disable-auto-cleanup");
    }
    command
        .env("OMPI_ALLOW_RUN_AS_ROOT", "1")
        .env("OMPI_ALLOW_RUN_AS_ROOT_CONFIRM", "1")
        .env("OPENBLAS_NUM_THREADS", "1")
        .env("OMP_NUM_THREADS", "1");
    command
}

/// Copy `source` (inputs and `zqp_opt.dat`) to a fresh directory next to it.
#[cfg(feature = "mpi")]
fn copy_inputs(source: &Path, target: &Path) {
    fs::create_dir_all(target).unwrap();
    for entry in fs::read_dir(source).unwrap().flatten() {
        if entry.path().is_file() {
            fs::copy(entry.path(), target.join(entry.file_name())).unwrap();
        }
    }
}

/// `-m 2` at 2, 3 and 4 ranks (2x1, 2+1 with the C load-imbalance warning, 2x2): each
/// group's output equals a standalone run of its directory at the group's width and
/// matches the native C `-m 2` fixture of the same world size.
#[cfg(feature = "mpi")]
#[test]
#[ignore = "requires a live MPI launcher; run explicitly in the MPI verification environment"]
fn multidef_groups_match_own_single_runs_and_c_fixture() {
    for world in [2_usize, 3, 4] {
        let dir = TestDir::new(&format!("mpi-{world}"));
        setup(&dir.0);
        let output = mpi_cli_command()
            .current_dir(&dir.0)
            .arg("-n")
            .arg(world.to_string())
            .arg(env!("CARGO_BIN_EXE_mvmc"))
            .args(["-m", "2", "dirs.txt", "namelist.def", "zqp_opt.dat"])
            .output()
            .unwrap();
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(output.status.success(), "{world} ranks: {stderr}");
        // C prints the imbalance warning once, on rank 0, and nothing else on stderr.
        let expected_stderr = c_message(&format!("r{world}_stderr.txt"));
        let remark = stderr
            .lines()
            .filter(|line| line.starts_with("warning:") || line.starts_with("error:"))
            .collect::<Vec<_>>()
            .join("\n");
        assert_eq!(remark, expected_stderr, "{world} ranks stderr");
        // Each group's banner comes from its own rank 0 (one per group).
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert_eq!(stdout.matches("=== Completed").count(), 2, "{stdout}");

        for (index, name) in ["a", "b"].into_iter().enumerate() {
            let width = mvmc_core::multidef::group_size(index, world, 2);
            let single = TestDir::new(&format!("single-{world}-{name}"));
            let inputs = single.0.join("run");
            copy_inputs(&dir.0.join(name), &inputs);
            let mut command = if width == 1 {
                mvmc()
            } else {
                let mut command = mpi_cli_command();
                command
                    .arg("-n")
                    .arg(width.to_string())
                    .arg(env!("CARGO_BIN_EXE_mvmc"));
                command
            };
            let run = command
                .current_dir(&inputs)
                .args(["namelist.def", "zqp_opt.dat"])
                .output()
                .unwrap();
            assert!(
                run.status.success(),
                "{}",
                String::from_utf8_lossy(&run.stderr)
            );
            let group_output = dir.0.join(name).join("output");
            assert_outputs_close(
                &group_output,
                &inputs.join("output"),
                1e-12,
                &format!("{world} ranks group {name} vs standalone width {width}"),
            );
            assert_outputs_close(
                &group_output,
                &fixture(&format!("c/r{world}/{name}")),
                1e-9,
                &format!("{world} ranks group {name} vs native C"),
            );
        }
        // The two groups really ran different inputs.
        let a = numbers(&dir.0.join("a/output/zvo_out_001.dat"));
        let b = numbers(&dir.0.join("b/output/zvo_out_001.dat"));
        assert!(a.iter().zip(&b).any(|(x, y)| (x - y).abs() > 1e-3));
    }
}

/// A failing group directory aborts every rank with status 1 before any calculation.
#[cfg(feature = "mpi")]
#[test]
#[ignore = "requires a live MPI launcher; run explicitly in the MPI verification environment"]
fn bad_group_directory_and_small_world_fail_collectively() {
    let dir = TestDir::new("mpi-bad");
    setup(&dir.0);
    fs::write(dir.0.join("bad.txt"), "a\nnope\n").unwrap();
    let output = mpi_cli_command()
        .current_dir(&dir.0)
        .args(["-n", "2"])
        .arg(env!("CARGO_BIN_EXE_mvmc"))
        .args(["-m", "2", "bad.txt", "namelist.def", "zqp_opt.dat"])
        .output()
        .unwrap();
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("error: chdir(): nope: No such file or directory"),
        "{stderr}"
    );
    assert!(!dir.0.join("a/output").exists());

    let output = mpi_cli_command()
        .current_dir(&dir.0)
        .args(["-n", "2"])
        .arg(env!("CARGO_BIN_EXE_mvmc"))
        .args(["-m", "3", "dirs.txt", "namelist.def", "zqp_opt.dat"])
        .output()
        .unwrap();
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert_eq!(
        stderr
            .lines()
            .filter(|line| line.starts_with("error: -m"))
            .count(),
        1,
        "{stderr}"
    );
    assert!(stderr.contains("error: -m: N should be smaller than MPI size."));
}
