//! #344: the modpara.def reader follows C `SetDefaultValuesModPara` /
//! `GetInfoFromModPara`. Expected values come from the C oracle fixture
//! `tests/fixtures/modpara_reader/c_reader.txt` (generated by
//! `scripts/check_modpara_reader_c_parity.py`, see its provenance header).
//! This test reads fixtures only; it never compiles or runs C.
#[path = "../../../tests/support/numerical_comparison.rs"]
mod numerical_comparison;

use std::collections::BTreeMap;
use std::path::PathBuf;

use mvmc_expert_parsers::parsers::modpara::{parse_modpara_content, parse_modpara_def};
use mvmc_expert_parsers::ModParaParameters;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/modpara_reader")
}

#[derive(Default)]
struct Case {
    status: i32,
    rejected_keyword: Option<String>,
    ints: BTreeMap<String, i64>,
    doubles: BTreeMap<String, f64>,
    strings: BTreeMap<String, String>,
}

fn load_cases() -> BTreeMap<String, Case> {
    let text = std::fs::read_to_string(fixture_dir().join("c_reader.txt")).unwrap();
    let mut cases = BTreeMap::new();
    let mut current: Option<(String, Case)> = None;
    for line in text.lines().filter(|l| !l.starts_with('#')) {
        let (kind, rest) = line.split_once(' ').unwrap();
        if kind == "case" {
            if let Some((name, case)) = current.take() {
                cases.insert(name, case);
            }
            let (name, status) = rest.split_once(" status ").unwrap();
            current = Some((
                name.to_owned(),
                Case {
                    status: status.parse().unwrap(),
                    ..Case::default()
                },
            ));
            continue;
        }
        let case = &mut current.as_mut().unwrap().1;
        if kind == "rejected_keyword" {
            case.rejected_keyword = Some(rest.to_owned());
            continue;
        }
        let (key, value) = rest.split_once(' ').unwrap();
        match kind {
            "int" => drop(case.ints.insert(key.to_owned(), value.parse().unwrap())),
            "double" => drop(case.doubles.insert(key.to_owned(), value.parse().unwrap())),
            "str" => drop(case.strings.insert(key.to_owned(), value.to_owned())),
            other => panic!("unknown fixture line kind {other}"),
        }
    }
    let (name, case) = current.unwrap();
    cases.insert(name, case);
    cases
}

fn rust_ints(p: &ModParaParameters) -> Vec<(&'static str, i64)> {
    vec![
        ("NVMCCalMode", p.vmc_calc_mode),
        ("NLanczosMode", p.lanczos_mode),
        ("NDataIdxStart", p.n_data_idx_start),
        ("NDataQtySmp", p.n_data_qty_smp),
        ("Nsite", p.nsite),
        ("Ne", p.nelec),
        ("Ncond", p.ncond),
        ("2Sz", p.two_sz),
        ("NSPGaussLeg", p.nsp_gauss_leg),
        ("NSPStot", p.nsp_stot),
        ("NMPTrans", p.nmp_trans),
        ("NSROptItrStep", p.nsr_opt_itr_step),
        ("NSROptItrSmp", p.nsr_opt_itr_smp),
        ("NSROptFixSmp", p.nsr_opt_fix_smp),
        ("NSROptCGMaxIter", p.nsr_opt_cg_max_iter),
        ("NVMCWarmUp", p.nvmc_warmup),
        ("NVMCInterval", p.nvmc_interval),
        ("NVMCSample", p.nvmc_sample),
        ("NExUpdatePath", p.nex_update_path),
        ("NSplitSize", p.nsplit_size),
        ("Nneuron", p.nneuron),
        ("NneuronCharge", p.nneuron_charge),
        ("NneuronSpin", p.nneuron_spin),
        ("NneuronGeneral", p.nneuron_general),
        ("NBlockSize_RBMRatio", p.nblock_size_rbm_ratio),
        ("NStore", p.nstore_o),
        ("NSRCG", p.nsrcg),
    ]
}

#[test]
fn modpara_reader_matches_c_oracle_for_accepted_and_rejected_inputs() {
    let cases = load_cases();
    assert!(cases.len() >= 40, "fixture must cover about 40 variants");
    let mut accepted = 0;
    let mut rejected = 0;
    for (name, case) in &cases {
        let path = fixture_dir().join("inputs").join(format!("{name}.def"));
        let parsed = parse_modpara_def(&path);
        if case.status != 0 {
            rejected += 1;
            let error = parsed.expect_err(name);
            if let Some(keyword) = &case.rejected_keyword {
                assert!(
                    error.to_string().contains(keyword.as_str()),
                    "{name}: error must name keyword {keyword}: {error}"
                );
            }
            continue;
        }
        accepted += 1;
        let p = parsed.unwrap_or_else(|e| panic!("{name}: {e}"));
        // Integer contract: exact.
        for (key, value) in rust_ints(&p) {
            assert_eq!(value, case.ints[key], "{name}: {key}");
        }
        // RndSeed < 0 is replaced by time(NULL) in C (sentinel in the oracle).
        // Rust keeps the raw value and resolve_rnd_seed applies it exactly once.
        let c_seed = case.ints["RndSeed"];
        if c_seed == case.ints["TimeSentinel"] {
            assert!(p.rnd_seed < 0, "{name}: C replaced a negative seed");
        } else {
            assert_eq!(p.rnd_seed, c_seed, "{name}: RndSeed");
        }
        // Doubles are strtod results; no arithmetic is involved, so a tight
        // relative bound (docs/NUMERICAL_COMPARISONS.md) is conservative.
        for (key, value) in [
            ("DSROptRedCut", p.dsr_opt_red_cut),
            ("DSROptStaDel", p.dsr_opt_sta_del),
            ("DSROptStepDt", p.dsr_opt_step_dt),
            ("DSROptCGTol", p.dsr_opt_cg_tol),
        ] {
            assert!(
                numerical_comparison::within(value, case.doubles[key], 0.0, 1e-15),
                "{name}: {key} {value} vs {}",
                case.doubles[key]
            );
        }
        assert_eq!(
            p.c_data_file_path_head(),
            case.strings["CDataFileHead"],
            "{name}"
        );
        assert_eq!(
            p.c_para_file_path_head(),
            case.strings["CParaFileHead"],
            "{name}"
        );
    }
    assert!(
        accepted >= 20 && rejected >= 15,
        "{accepted} accepted, {rejected} rejected"
    );
}

#[test]
fn in_memory_parser_agrees_with_file_parser() {
    let dir = fixture_dir().join("inputs");
    let text = std::fs::read_to_string(dir.join("full_typical.def")).unwrap();
    assert_eq!(
        parse_modpara_content(&text).unwrap(),
        parse_modpara_def(dir.join("full_typical.def")).unwrap()
    );
}

#[test]
fn rust_only_keywords_are_rejected_naming_the_keyword() {
    for keyword in [
        "NElec",
        "NSite",
        "VMCCalMode",
        "useDiagScale",
        "RescaleSmat",
        "NFileFlushInterval",
        "ComplexType",
        "NSROptFixSmp",
    ] {
        let header = "-\nModel_Parameters 0\n-\nVMC_Cal_Parameters\n-\nCDataFileHead zvo\nCParaFileHead zqp\n-\n";
        let result = parse_modpara_content(&format!("{header}{keyword} 1\n"));
        // C `Nsite` is case-insensitive, so NSite is the C keyword Nsite.
        if keyword == "NSite" {
            assert_eq!(result.unwrap().nsite, 1);
            continue;
        }
        let error = result.unwrap_err().to_string();
        assert!(error.contains(keyword), "{keyword}: {error}");
    }
}

#[test]
fn c_defaults_apply_to_absent_keys() {
    // readdef.c:1756-1823.
    let p = ModParaParameters::default();
    assert_eq!(
        (
            p.nsite,
            p.nelec,
            p.nvmc_warmup,
            p.nvmc_sample,
            p.nsr_opt_itr_smp
        ),
        (16, 8, 10, 10, 100)
    );
    assert_eq!(
        (p.nex_update_path, p.nstore_o, p.nsr_opt_fix_smp),
        (0, 1, 1)
    );
    assert_eq!(
        (p.dsr_opt_red_cut, p.dsr_opt_sta_del, p.dsr_opt_step_dt),
        (0.001, 0.02, 0.02)
    );
}
