[package]
name = "mvmc-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
num-complex = { workspace = true }
serde = { workspace = true }
mvmc-physics = { path = "../mvmc-physics" }
rand = { workspace = true }
mvmc-bindings = { path = "../mvmc-bindings" }

[dev-dependencies]
approx = { workspace = true }
proptest = { workspace = true }
