#!/usr/bin/env python3
"""Optional C probe for `_time_`/`_SRinfo` run-log formats (issue #346).

Extracts verbatim mVMC-1.3.0 bodies into c_toolbox/time_srinfo_*.inc, builds
c_toolbox/time_srinfo_format.c and writes the output files to
tests/fixtures/time_srinfo_c/. Rust tests read only the checked-in fixture.

    uv run --no-project python scripts/check_time_srinfo_c_parity.py --write
    uv run --no-project python scripts/check_time_srinfo_c_parity.py        # verify

Pass --source <mVMC-1.3.0 checkout> when extern/mVMC-1.3.0 is not populated.
"""
import argparse
import filecmp
import hashlib
import os
import platform
import subprocess
import sys
import tempfile
from pathlib import Path

LICENSE_NOTE = ("/* Verbatim lines from authoritative mVMC-1.3.0 (GPL-3.0-or-later, "
                "Copyright (C) 2016 The University of Tokyo).\n * Regenerate with "
                "scripts/check_time_srinfo_c_parity.py --write. Optional oracle, not a Rust "
                "build/test dependency. */\n")
CFLAGS = ["-std=gnu11", "-O0", "-ffp-contract=off"]
SUBMODULE_COMMIT = "d73d06bd529d3b2573f38eb5817c4a5f52971006"


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def lines(src, first, last, must_start):
    text = src.read_text().split("\n")
    chunk = text[first - 1:last]
    assert chunk[0].lstrip().startswith(must_start), (src, first, chunk[0])
    return "\n".join(chunk) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--source", type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    mvmc = (args.source or root / "extern/mVMC-1.3.0") / "src/mVMC"
    tool = root / "c_toolbox"
    parts = {
        "time_srinfo_upstream.inc": [
            (mvmc / "initfile.c", 33, 70, "void InitFile("),
            (mvmc / "initfile.c", 144, 156, "void CloseFile("),
            (mvmc / "initfile.c", 192, 204, "void FlushFile("),
            (mvmc / "vmcclock.c", 34, 48, "void OutputTime("),
        ],
        "time_srinfo_rows_direct.inc": [(mvmc / "stcopt.c", 157, 158, "fprintf(FileSRinfo")],
        "time_srinfo_rows_diag.inc": [(mvmc / "stcopt_pdposv.c", 585, 586, "fprintf(FileSRinfo")],
        "time_srinfo_rows_cg.inc": [(mvmc / "stcopt_cg_impl.c", 202, 203, "fprintf(FileSRinfo")],
    }
    sources = sorted({p[0] for v in parts.values() for p in v})
    for name, spec in parts.items():
        body = LICENSE_NOTE + "".join(
            f"/* {s.name}:{a}-{b} sha256={sha(s)} */\n" + lines(s, a, b, st)
            for s, a, b, st in spec)
        target = tool / name
        if args.write:
            target.write_text(body)
        elif target.read_text() != body:
            sys.exit(f"{name} differs from upstream extraction")
    fixture = root / "tests/fixtures/time_srinfo_c"
    with tempfile.TemporaryDirectory(prefix="mvmc-time-srinfo-") as tmp:
        exe = Path(tmp) / "probe"
        subprocess.run(["cc", *CFLAGS, str(tool / "time_srinfo_format.c"), "-o", str(exe)],
                       check=True)
        out = Path(tmp) / "out"
        out.mkdir()
        subprocess.run([str(exe), str(out)], check=True, env={**os.environ, "TZ": "UTC"})
        compiler = subprocess.run(["cc", "--version"], capture_output=True, text=True).stdout
        if args.write:
            fixture.mkdir(parents=True, exist_ok=True)
            for f in sorted(out.rglob("*_time_*.dat")) + sorted(out.rglob("*_SRinfo.dat")):
                dest = fixture / f.relative_to(out)
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(f.read_bytes())
            hashes = "\n".join(f"- `src/mVMC/{s.name}`: `{sha(s)}`" for s in sources)
            (fixture / "PROVENANCE.md").write_text(
                "# C `_time_` / `_SRinfo` format fixtures (issue #346)\n\n"
                "Generated by `uv run --no-project python scripts/check_time_srinfo_c_parity.py "
                "--write`.\n\n"
                "- Probe: `c_toolbox/time_srinfo_format.c` (standalone kernel check; verbatim "
                "`InitFile`, `CloseFile`, `FlushFile`, `OutputTime` and the SRinfo `fprintf` "
                "statements from mVMC-1.3.0; no MPI/sampler/solver, counters and solver values "
                "are literals; `time()` stubbed to 1700000000, run with `TZ=UTC`). A full C "
                "executable run was not possible (no MPI toolchain).\n"
                f"- Compiler: `cc {' '.join(CFLAGS)}`; `{compiler.splitlines()[0]}`; "
                f"{platform.system()} {platform.machine()}.\n"
                f"- Upstream submodule commit `{SUBMODULE_COMMIT}`; source SHA-256:\n"
                + hashes + "\n\n"
                "Inputs per case are the literals in the probe's `main`. `paraopt/` uses "
                "`NFileFlushInterval=2`, `NDataIdxStart=7`; `physcal/` is `NVMCCalMode=1` with "
                "`NDataIdxStart=-1`; `diag/` is `SRFlag=1`.\n")
        else:
            for f in sorted(out.rglob("*_time_*.dat")) + sorted(out.rglob("*_SRinfo.dat")):
                if not filecmp.cmp(f, fixture / f.relative_to(out), shallow=False):
                    sys.exit(f"{f.relative_to(out)} differs from checked-in fixture")


if __name__ == "__main__":
    main()
