#!/usr/bin/env python3
"""Optional #350 oracle: the unmodified C ComplexUHF executable.

Builds `extern/mVMC-1.3.0/src/ComplexUHF` exactly as its CMakeLists lists it
(plus the common/SFMT sources it links) with the host C compiler and
OpenBLAS, runs the cases generated by `c_toolbox/complex_uhf/cases.py`, and
stores inputs, C outputs and provenance under `tests/fixtures/complex_uhf/`.
This is a *full C executable* check of the ComplexUHF tool (no MPI and no
sampling are involved); Rust tests only read the stored fixtures.

    uv run --no-project python scripts/check_complex_uhf_c_parity.py --write
    uv run --no-project python scripts/check_complex_uhf_c_parity.py    # byte check

The byte check is meaningful only on the platform/BLAS recorded in
`tests/fixtures/complex_uhf/PROVENANCE.txt`.
"""
import argparse
import ctypes
import ctypes.util
import hashlib
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "c_toolbox/complex_uhf"))
from cases import build_cases  # noqa: E402

SOURCES = [
    "UHFmain.c", "output.c", "cal_energy.c", "green.c", "makeham.c", "diag.c",
    "initial.c", "matrixlapack.c", "readdef.c",
]
FIXTURES = ROOT / "tests/fixtures/complex_uhf"
CFLAGS = ["-O2", "-ffp-contract=off", "-fopenmp", "-DMEXP=19937"]


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def build(directory):
    uhf = ROOT / "extern/mVMC-1.3.0/src/ComplexUHF"
    src = ROOT / "extern/mVMC-1.3.0/src"
    binary = Path(directory) / "UHF"
    command = (["cc"] + CFLAGS + ["-I", str(uhf / "include"), "-I", str(src / "common"),
                                  "-I", str(src / "sfmt")]
               + [str(uhf / name) for name in SOURCES]
               + [str(src / "common/setmemory.c"), str(src / "sfmt/SFMT.c"), "-o", str(binary),
                  "-lopenblas", "-lm"])
    subprocess.run(command, check=True, capture_output=True)
    return binary, command


def run_case(binary, files):
    with tempfile.TemporaryDirectory(prefix="mvmc-c-uhf-") as work:
        work = Path(work)
        for name, text in files.items():
            (work / name).write_text(text)
        result = subprocess.run([str(binary), "namelist.def"], cwd=work, capture_output=True,
                                text=True, timeout=120)
        outputs = {p.name: p.read_text() for p in sorted(work.iterdir())
                   if p.name.startswith(("zvo_", "zqp_")) and p.suffix == ".dat"}
        return result.returncode, outputs


def blas_provenance():
    lines = []
    name = ctypes.util.find_library("openblas")
    if name:
        lib = ctypes.CDLL(name)
        lib.openblas_get_config.restype = ctypes.c_char_p
        lines.append(f"openblas config: {lib.openblas_get_config().decode()}")
    resolved = subprocess.run(["bash", "-c", "ldconfig -p | grep -m1 libopenblas.so.0"],
                              capture_output=True, text=True).stdout.strip()
    lines.append(f"openblas library: {resolved}")
    package = subprocess.run(["bash", "-c", "dpkg -l 'libopenblas0*' 2>/dev/null | grep '^ii'"],
                             capture_output=True, text=True).stdout.strip()
    if package:
        lines.append("openblas package: " + package.replace("\n", "; "))
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    cases = build_cases(ROOT)
    with tempfile.TemporaryDirectory(prefix="mvmc-c-uhf-build-") as directory:
        binary, command = build(directory)
        results = {name: run_case(binary, files) for name, files in cases.items()}
    uhf = ROOT / "extern/mVMC-1.3.0/src/ComplexUHF"
    hashed = [uhf / n for n in SOURCES] + sorted((uhf / "include").glob("*.h")) + [
        ROOT / "extern/mVMC-1.3.0/src/common/setmemory.c",
        ROOT / "extern/mVMC-1.3.0/src/sfmt/SFMT.c",
    ]
    cc_version = subprocess.check_output(["cc", "--version"], text=True).splitlines()[0]
    provenance = [
        "# C mVMC 1.3.0 ComplexUHF reference outputs (issue #350)",
        "# Unmodified C source of extern/mVMC-1.3.0/src/ComplexUHF run as the full UHF executable.",
        *(f"# {p.relative_to(ROOT)} sha256={sha256(p)}" for p in hashed),
        f"# compiler: {cc_version}",
        "# compile: cc " + " ".join(CFLAGS) + " -I extern/mVMC-1.3.0/src/ComplexUHF/include"
        " -I extern/mVMC-1.3.0/src/common -I extern/mVMC-1.3.0/src/sfmt "
        + " ".join(f"extern/mVMC-1.3.0/src/ComplexUHF/{n}" for n in SOURCES)
        + " extern/mVMC-1.3.0/src/common/setmemory.c extern/mVMC-1.3.0/src/sfmt/SFMT.c"
        " -o UHF -lopenblas -lm",
        f"# platform: {platform.system()} {platform.machine()} {platform.release()} "
        f"{platform.libc_ver()[0]} {platform.libc_ver()[1]}",
        *(f"# {line}" for line in blas_provenance()),
        "# case inputs: c_toolbox/complex_uhf/cases.py (verbatim upstream trees or generated)",
        "# reproduce: uv run --no-project python scripts/check_complex_uhf_c_parity.py --write",
        "# layout: <case>/input/*.def, <case>/expected/{zvo_*,zqp_*}.dat, <case>/status.txt (C exit code)",
    ]
    provenance_text = "\n".join(provenance) + "\n"
    if args.write:
        shutil.rmtree(FIXTURES, ignore_errors=True)
    for name, files in cases.items():
        returncode, outputs = results[name]
        base = FIXTURES / name
        if args.write:
            for sub, mapping in (("input", files), ("expected", outputs)):
                (base / sub).mkdir(parents=True, exist_ok=True)
                for file_name, text in mapping.items():
                    (base / sub / file_name).write_text(text)
            (base / "status.txt").write_text(f"{returncode}\n")
        else:
            assert (base / "status.txt").read_text() == f"{returncode}\n", name
            for file_name, text in outputs.items():
                assert (base / "expected" / file_name).read_text() == text, (name, file_name)
        print(f"{name}: C exit {returncode}, {len(outputs)} output files")
    if args.write:
        (FIXTURES / "PROVENANCE.txt").write_text(provenance_text)
    print(f"{len(cases)} ComplexUHF C cases {'written' if args.write else 'checked'}")


if __name__ == "__main__":
    main()
