using Printf
using PfaPack

const OUT_DIR = abspath(joinpath(@__DIR__, "..", "tests", "fixtures", "pfapack"))
const SIZES = (32, 64, 128, 256)
const SEED = UInt64(42)

function next_f64!(state::Base.RefValue{UInt64})
    state[] = state[] * UInt64(6364136223846793005) + UInt64(1442695040888963407)
    bits = UInt32(state[] >> 32)
    return (Float64(bits) / Float64(typemax(UInt32))) * 2.0 - 1.0
end

function skew_real(n::Int, seed::UInt64)
    s = Ref(seed + UInt64(0xdeadbeef))
    A = zeros(Float64, n, n)
    for j in 1:n, i in 1:j-1
        v = next_f64!(s)
        A[i, j] = v
        A[j, i] = -v
    end
    return A
end

function skew_complex(n::Int, seed::UInt64)
    s = Ref(seed + UInt64(0xdeadbeef))
    A = zeros(ComplexF64, n, n)
    for j in 1:n, i in 1:j-1
        v = ComplexF64(next_f64!(s), next_f64!(s))
        A[i, j] = v
        A[j, i] = -v
    end
    return A
end

function write_header(io, kind::String, n::Int, seed::UInt64, kind_value::String)
    println(io, "# Generated by scripts/dump_pfapack_large_reference.jl")
    println(io, "# DO NOT EDIT BY HAND -- re-run the dumper to refresh.")
    println(io, "kind $kind")
    println(io, "n $n")
    println(io, "seed $seed")
    println(io, "kind_value $kind_value")
    println(io)
end

function write_value(io, x::Float64)
    @printf(io, "%.17e\n", x)
end

function write_value(io, z::ComplexF64)
    @printf(io, "%.17e %.17e\n", real(z), imag(z))
end

function write_matrix(io, A)
    for x in A
        write_value(io, x)
    end
end

function dump_case(kind::String, n::Int, seed::UInt64, A)
    stem = "$(kind)_n$(n)_seed$(seed)"

    open(joinpath(OUT_DIR, "$stem.orig.txt"), "w") do io
        write_header(io, kind, n, seed, "orig")
        write_matrix(io, A)
    end

    ltl = copy(A)
    piv = zeros(Int, n)
    if kind == "real"
        info = julia_dsktf2!(ltl, piv)
    else
        info = julia_zsktf2!(ltl, piv)
    end
    info == 0 || error("LTL decomposition failed for $stem: info=$info")

    open(joinpath(OUT_DIR, "$stem.ltl.txt"), "w") do io
        write_header(io, kind, n, seed, "ltl")
        println(io, "# Trailing block: column-major n*n matrix entries")
        println(io, "# followed by n 1-based pivot indices, one per line.")
        write_matrix(io, ltl)
        for p in piv
            println(io, p)
        end
    end

    # Use the LTL form as the large-size Pfaffian reference. This is the
    # numerically consistent path for the mVMC hot path and satisfies
    # pf(A)^2 == det(A) on the generated complex cases.
    pf = utu2pfa(n, ltl, n, piv)
    open(joinpath(OUT_DIR, "$stem.pfaffian.txt"), "w") do io
        write_header(io, kind, n, seed, "pfaffian")
        write_value(io, pf)
    end

    inv = copy(ltl)
    vt = zeros(eltype(A), n - 1)
    work = zeros(eltype(A), n, n)
    utu2inv!(n, inv, n, piv, vt, work, n)
    open(joinpath(OUT_DIR, "$stem.inverse.txt"), "w") do io
        write_header(io, kind, n, seed, "inverse")
        write_matrix(io, inv)
    end
end

mkpath(OUT_DIR)
for n in SIZES
    dump_case("real", n, SEED, skew_real(n, SEED))
    dump_case("complex", n, SEED, skew_complex(n, SEED))
end
