/* Verbatim lines from authoritative mVMC-1.3.0 (GPL-3.0-or-later, Copyright (C) 2016 The University of Tokyo).
 * Regenerate with scripts/check_time_srinfo_c_parity.py --write. Optional oracle, not a Rust build/test dependency. */
/* stcopt.c:157-158 sha256=43ed8790cff2715284849f0f8906e4645179dcbb100b51f819918b279d6a36f2 */
    fprintf(FileSRinfo, "%5d %5d %5d %5d % .5e % .5e % .5e %5d\n",NPara,nSmat,optNum,cutNum,
            sDiagMax,sDiagMin,rmax,smatToParaIdx[simax]);
