/* Verbatim lines from authoritative mVMC-1.3.0 (GPL-3.0-or-later, Copyright (C) 2016 The University of Tokyo).
 * Regenerate with scripts/check_time_srinfo_c_parity.py --write. Optional oracle, not a Rust build/test dependency. */
/* stcopt_cg_impl.c:202-203 sha256=41452de5fe766409431c6e1cf73cd2b12485faaeb4bfbcdec1e53444e9af1cf9 */
    fprintf(FileSRinfo, "%5d %5d %5d %5d % .5e % .5e % .5e %5d, %d\n",NPara,nSmat,optNum,cutNum,
            sDiagMax,sDiagMin,rmax,smatToParaIdx[simax], info);
