/* Verbatim lines from authoritative mVMC-1.3.0 (GPL-3.0-or-later, Copyright (C) 2016 The University of Tokyo).
 * Regenerate with scripts/check_time_srinfo_c_parity.py --write. Optional oracle, not a Rust build/test dependency. */
/* stcopt_pdposv.c:585-586 sha256=0ce8e1fc14dcf1c5aa40d5255c519eef4403b32a0720d52181f29eb49aa66d13 */
    fprintf(FileSRinfo, "%5d %5d %5d %5d % .5e % .5e % .5e %5d\n",NPara,nSmat,optNum,cutIdx,
            eigenMax,eigenMin,rmax,smatToParaIdx[imax]);
